default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: POS_development

test:
  <<: *default
  database: POS_test

production:
  <<: *default
  database: POS_production
  username: POS
  password: <%= ENV['POS_DATABASE_PASSWORD'] %>
